coffee_harvest_seasons = {
    "Brazil": ["May–September"],
    "Colombia": ["September–December", "April–June (mitaca - secondary)"],
    "Ethiopia": ["October–January"],
    "Vietnam": ["October–February"],
    "Indonesia": ["May–October (mainly)", "October–March (Sumatra)"],
    "Honduras": ["November–April"],
    "India": ["October–March"],
    "Uganda": ["October–February", "March–June (robusta)"],
    "Mexico": ["November–March"],
    "Peru": ["April–September"],
    "Guatemala": ["December–April"],
    "Nicaragua": ["December–March"],
    "Costa Rica": ["November–March"],
    "Kenya": ["October–December", "June–August (fly crop)"],
    "Tanzania": ["July–December"],
    "El Salvador": ["December–March"],
    "Rwanda": ["March–June", "September–December"],
    "Burundi": ["March–July"],
    "Yemen": ["October–February"],
    "Panama": ["October–March"],
    "Dominican Republic": ["August–March"],
    "Ecuador": ["April–August", "October–February"],
    "Bolivia": ["June–September"],
    "Cameroon": ["October–March"],
    "Papua New Guinea": ["April–September"],
    "Thailand": ["November–March"],
    "Laos": ["October–March"],
    "China": ["October–February"],
    "Zambia": ["April–September"],
    "Malawi": ["April–August"],
    "Haiti": ["April–August"],
}
